tenant: ac360 # Enter your tenant name here
app: demos # Enter your application name here
service: fullstack-restapi # update

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  environment:
    database_submissions_name: ${state:fullstack-database.database_submissions_name}
    database_submissions_region: ${state:fullstack-database.database_submissions_region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:*:*:table/${state:fullstack-database.database_submissions_name}"

functions:
  formSubmit:
    handler: index.submit
    timeout: 6
    events:
      - http:
          path: submit
          method: post
          cors: true
