tenant: ac360 # Enter your tenant name here
app: demos # Enter your application name here
service: fullstack-website

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1

plugins:
  - serverless-finch

custom:
  client:
    bucketName: demo-fullstack-ja189j # Change this to a universally unique bucket name
    distributionFolder: ./build
